[2024-04-08T15:03:40.384+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: seed_initial_data.insert_coins_into_db manual__2024-04-08T15:03:37.896666+00:00 [queued]>
[2024-04-08T15:03:40.389+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: seed_initial_data.insert_coins_into_db manual__2024-04-08T15:03:37.896666+00:00 [queued]>
[2024-04-08T15:03:40.390+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-04-08T15:03:40.397+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): insert_coins_into_db> on 2024-04-08 15:03:37.896666+00:00
[2024-04-08T15:03:40.401+0000] {standard_task_runner.py:57} INFO - Started process 28109 to run task
[2024-04-08T15:03:40.405+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'seed_initial_data', 'insert_coins_into_db', 'manual__2024-04-08T15:03:37.896666+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/file_procesor_dag.py', '--cfg-path', '/tmp/tmpsnvfr6v4']
[2024-04-08T15:03:40.407+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask insert_coins_into_db
[2024-04-08T15:03:40.450+0000] {task_command.py:416} INFO - Running <TaskInstance: seed_initial_data.insert_coins_into_db manual__2024-04-08T15:03:37.896666+00:00 [running]> on host 2c889d8e7a74
[2024-04-08T15:03:40.517+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='seed_initial_data' AIRFLOW_CTX_TASK_ID='insert_coins_into_db' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T15:03:37.896666+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-08T15:03:37.896666+00:00'
[2024-04-08T15:03:40.519+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: dummy_test() missing 1 required positional argument: 'config'
[2024-04-08T15:03:40.533+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=seed_initial_data, task_id=insert_coins_into_db, execution_date=20240408T150337, start_date=20240408T150340, end_date=20240408T150340
[2024-04-08T15:03:40.545+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 11 for task insert_coins_into_db (dummy_test() missing 1 required positional argument: 'config'; 28109)
[2024-04-08T15:03:40.578+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-04-08T15:03:40.598+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
