[2024-04-08T19:03:15.769+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: seed_initial_data.insert_coins_into_db manual__2024-04-08T19:03:13.207232+00:00 [queued]>
[2024-04-08T19:03:15.778+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: seed_initial_data.insert_coins_into_db manual__2024-04-08T19:03:13.207232+00:00 [queued]>
[2024-04-08T19:03:15.779+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-04-08T19:03:15.790+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): insert_coins_into_db> on 2024-04-08 19:03:13.207232+00:00
[2024-04-08T19:03:15.796+0000] {standard_task_runner.py:57} INFO - Started process 75117 to run task
[2024-04-08T19:03:15.800+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'seed_initial_data', 'insert_coins_into_db', 'manual__2024-04-08T19:03:13.207232+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/file_procesor_dag.py', '--cfg-path', '/tmp/tmps6jr_non']
[2024-04-08T19:03:15.803+0000] {standard_task_runner.py:85} INFO - Job 30: Subtask insert_coins_into_db
[2024-04-08T19:03:15.866+0000] {task_command.py:416} INFO - Running <TaskInstance: seed_initial_data.insert_coins_into_db manual__2024-04-08T19:03:13.207232+00:00 [running]> on host 2c889d8e7a74
[2024-04-08T19:03:15.952+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='seed_initial_data' AIRFLOW_CTX_TASK_ID='insert_coins_into_db' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T19:03:13.207232+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-08T19:03:13.207232+00:00'
[2024-04-08T19:03:15.955+0000] {logging_mixin.py:154} INFO - {'origin_path': 'scripts/data/config/nyse_2012.csv', 'final_path': 'nyse_2012_ts.parquet', 'metadata': {'type': 'delimited', 'columns_width': [6, 24, 7, 7, 7, 7, 7], 'columns_name': ['stock', 'transaction_date', 'open_price', 'close_price', 'max_price', 'min_price', 'variation'], 'additional_data': {}}, 'partition_by': 'stock'}
[2024-04-08T19:03:15.959+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/main.py", line 14, in procesar_archivo
    df = strategy.load_data(config)
  File "/opt/airflow/scripts/strategies/read.py", line 14, in load_data
    return pd.read_csv(full_path, delimiter=',')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scripts/data/config/nyse_2012.csv'
[2024-04-08T19:03:15.971+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=seed_initial_data, task_id=insert_coins_into_db, execution_date=20240408T190313, start_date=20240408T190315, end_date=20240408T190315
[2024-04-08T19:03:15.979+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 30 for task insert_coins_into_db ([Errno 2] No such file or directory: '/opt/airflow/scripts/data/config/nyse_2012.csv'; 75117)
[2024-04-08T19:03:16.013+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-04-08T19:03:16.033+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
